apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-itpa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-itpa
    app.kubernetes.io/part-of: tkrw-pr714-0075-0055-app
  name: devfile-sample-itpa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-itpa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-itpa
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0055-tenant/tkrw-pr714-0075-0055-app/devfile-sample-itpa@sha256:2e77f2ceb42077028696f4d0eef9d2aeb247c598e708e7057b24ddf82952fa5b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
